export const categories = [
  {
    name: "Food",
    unselectedIcon: "restaurant-outline",
    selectedIcon: "restaurant",
    color: "wheat",
  },
  {
    name: "Transport",
    unselectedIcon: "car-outline",
    selectedIcon: "car",
    color: "yellow",
  },
  {
    name: "Entertainment",
    unselectedIcon: "game-controller-outline",
    selectedIcon: "game-controller",
    color: "lightcoral",
  },
  {
    name: "Shopping",
    unselectedIcon: "cart-outline",
    selectedIcon: "cart",
    color: "aqua",
  },
  {
    name: "Salary",
    unselectedIcon: "cash-outline",
    selectedIcon: "cash",
    color: "lightgreen",
  },
  {
    name: "Investment",
    unselectedIcon: "cash-outline",
    selectedIcon: "cash",
    color: "orange",
  },
  {
    name: "Petrol / Gas",
    unselectedIcon: "car-sport-outline",
    selectedIcon: "car-sport",
    color: "burlywood",
  },
  {
    name: "Medical",
    unselectedIcon: "medkit-outline",
    selectedIcon: "medkit",
    color: "peachpuff",
  },
  {
    name: "Clothes",
    unselectedIcon: "shirt-outline",
    selectedIcon: "shirt",
    color: "lightcoral",
  },
  {
    name: "Rent",
    unselectedIcon: "home-outline",
    selectedIcon: "home",
    color: "pink",
  },
  {
    name: "Other Bills",
    unselectedIcon: "document-text-outline",
    selectedIcon: "document-text",
    color: "lightgray",
  },
  {
    name: "Education",
    unselectedIcon: "school-outline",
    selectedIcon: "school",
    color: "lightgreen",
  },
  {
    name: "Travel",
    unselectedIcon: "globe-outline",
    selectedIcon: "globe",
    color: "orange",
  },
  {
    name: "Other",
    unselectedIcon: "ellipsis-horizontal-outline",
    selectedIcon: "ellipsis-horizontal",
    color: "plum",
  },
];
