import { StyleSheet } from "react-native";
import useTheme from "../hooks/useTheme";

const createBanksStyles = () => {
  const { colors } = useTheme();
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    content: {
      flex: 1,
      padding: 24,
    },
    header: {
      marginBottom: 24,
    },
    title: {
      fontSize: 28,
      color: colors.text,
    },
    section: {
      borderRadius: 20,
      padding: 15,
      shadowColor: colors.shadow,
      borderWidth: 1,
      borderColor: colors.border,
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4, // elevation is used to create a shadow on the section, in android
      marginBottom: 15,
    },
    carouselContainer: {
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
      marginBottom: 20,
    },
    carouselItem: {
      alignItems: "center",
      justifyContent: "center",
      padding: 12,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      height: "100%",
      width: "100%",
    },
    carouselImage: {
      width: 60,
      height: 60,
      borderRadius: 10,
      marginBottom: 10,
    },
    carouselName: {
      fontSize: 18,
      color: colors.text,
      fontWeight: "600",
    },
    carouselItemDeleteButton: {
      position: "absolute",
      top: 0,
      right: 0,
      padding: 10,
    },
    carouselItemDeleteButtonIcon: {
      width: 20,
      height: 20,
      color: colors.danger,
    },
    carouselItemContentTop: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 10,
    },
    carouselItemContentBottom: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginTop: 10,
    },
    carouselIfsc: {
      fontSize: 14,
      color: colors.text,
      fontWeight: "400",
    },
    paginationDotsContainer: undefined,
    paginationDot: undefined,
    paginationDotActive: undefined,
    listContentContainer: {
      paddingBottom: 12,
      flexGrow: 1,
    },
    bankListItem: {
      marginBottom: 12,
    },
    bankCard: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
      backgroundColor: colors.surface,
    },
    bankLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      flex: 1,
    },
    bankText: {
      flex: 1,
    },
    ifscBadge: {
      alignSelf: "flex-start",
      marginTop: 6,
      backgroundColor: colors.backgrounds.input,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    ifscBadgeText: {
      fontSize: 12,
      color: colors.textMuted,
      letterSpacing: 0.3,
    },
    bankRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginLeft: 12,
    },
    deleteIconWrap: undefined,
    chevronWrap: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 6,
      borderRadius: 8,
    },
    chevronWrapExpanded: {
      transform: [{ rotate: "180deg" }],
    },
    expandedContainer: {
      marginTop: 8,
      marginHorizontal: 12,
      padding: 12,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 8,
    },
    expandedActions: {
      marginTop: 4,
    },
    deleteButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.danger,
      paddingVertical: 10,
      borderRadius: 10,
    },
    deleteButtonText: {
      color: colors.surface,
      fontSize: 14,
      fontWeight: "600",
    },
    detailRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    detailLabel: {
      color: colors.textMuted,
      fontSize: 12,
    },
    detailValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "500",
    },
    emptyCarouselText: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "600",
      textAlign: "center",
    },
    dropdownContainer: {
      marginBottom: 20,
    },
    dropdownTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 12,
    },
    bankContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: colors.surface,
      borderRadius: 8,
      marginVertical: 2,
    },
    bankLogo: {
      width: 32,
      height: 32,
      borderRadius: 16,
      marginRight: 12,
    },
    bankName: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "500",
    },
    ifscContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: colors.surface,
      borderRadius: 8,
      marginVertical: 2,
    },
    ifscName: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "500",
      flex: 1,
    },
    ifsc: {
      fontSize: 14,
      color: "#B0B0B0",
      fontWeight: "400",
      fontFamily: "monospace",
    },
    saveButton: {
      marginTop: 20,
      width: "70%",
      alignSelf: "center",
      padding: 8,
      borderRadius: 100,
      backgroundColor: colors.primary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
    },
    saveButtonText: {
      color: colors.surface,
      fontSize: 24,
      textAlign: "center",
    },
    footer: {
      paddingVertical: 24,
      alignItems: "center",
      justifyContent: "center",
    },
    footerText: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "600",
    },
  });
};

export default createBanksStyles;
